sites:
  #url: "http://112.26.166.27:18000"
  url: "http://222.195.83.28:18000"
  api: "/getDetectionNetworkStatesApi"
trigger: 
  #url: "http://112.26.166.27:18000"
  url: "http://222.195.83.28:18000"
  api: "/getHistoricalTrigger/20230719015506/10"
  api_nt: "/getHistoricalTrigger/"
  api_rt: "/getRealTimeTrigger/str/5"
ligresult:
  url: "http://112.26.166.27:18000"
  api: "/writeLigResult"
scale: 20
waitTime: 180
mode: realTime   # reProcess realTime
reProcess:
  #startTime: 20230807T080300
  #endTime: 20230807T080500
  startTime: 20230701T000000
  endTime: 20230701T002000
checkTheta: 45
expTag: 021905
maxBaseLineAsTOA: 0.005 # 1500 km
LocThresholdInitial: 15.0 # sq par station
LocThresholdFinal: 7.0 #sq par station
OutputFilePath: "D:\\sources\\LigDataParsing\\lig_txt\\"